### ISSUE TITLE
1.17.1 support

### ISSUE THREAD

**Issue by x1p** [ItsLewizzz/InventoryFullPlus#5]
Can you please add 1.17.1 support?
```
[12:50:50] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.EntityPlayer
[12:50:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[12:50:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[12:50:50] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[12:50:50] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[12:50:50] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[12:50:50] [Server thread/WARN]: 	at fun.lewisdev.inventoryfull.utils.reflection.ReflectionUtils.getNMSClass(ReflectionUtils.java:63)
[12:50:50] [Server thread/WARN]: 	at fun.lewisdev.inventoryfull.utils.reflection.ReflectionUtils.<clinit>(ReflectionUtils.java:40)
[12:50:50] [Server thread/WARN]: 	at fun.lewisdev.inventoryfull.utils.reflection.Titles.<clinit>(Titles.java:64)
[12:50:50] [Server thread/WARN]: 	at fun.lewisdev.inventoryfull.alert.AlertManager.sendTitle(AlertManager.java:52)
[12:50:50] [Server thread/WARN]: 	at fun.lewisdev.inventoryfull.alert.AlertManager.sendAlerts(AlertManager.java:33)
[12:50:50] [Server thread/WARN]: 	at fun.lewisdev.inventoryfull.listeners.BlockBreakListener.onBlockBreak(BlockBreakListener.java:60)
[12:50:50] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor668.execute(Unknown Source)
[12:50:50] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[12:50:50] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[12:50:50] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:50:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:401)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:355)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:290)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1787)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1422)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1400)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1393)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1532)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1270)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[12:50:50] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[12:50:50] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.PlayerConnection
[12:50:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[12:50:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[12:50:50] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[12:50:50] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[12:50:50] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[12:50:50] [Server thread/WARN]: 	at fun.lewisdev.inventoryfull.utils.reflection.ReflectionUtils.getNMSClass(ReflectionUtils.java:63)
[12:50:50] [Server thread/WARN]: 	at fun.lewisdev.inventoryfull.utils.reflection.ReflectionUtils.<clinit>(ReflectionUtils.java:42)
[12:50:50] [Server thread/WARN]: 	at fun.lewisdev.inventoryfull.utils.reflection.Titles.<clinit>(Titles.java:64)
[12:50:50] [Server thread/WARN]: 	at fun.lewisdev.inventoryfull.alert.AlertManager.sendTitle(AlertManager.java:52)
[12:50:50] [Server thread/WARN]: 	at fun.lewisdev.inventoryfull.alert.AlertManager.sendAlerts(AlertManager.java:33)
[12:50:50] [Server thread/WARN]: 	at fun.lewisdev.inventoryfull.listeners.BlockBreakListener.onBlockBreak(BlockBreakListener.java:60)
[12:50:50] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor668.execute(Unknown Source)
[12:50:50] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[12:50:50] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[12:50:50] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:50:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:401)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:355)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:290)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1787)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1422)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1400)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1393)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1532)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1270)
[12:50:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[12:50:50] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[12:50:50] [Server thread/ERROR]: Could not pass event BlockBreakEvent to InventoryFullPlus v2.5.9
java.lang.ExceptionInInitializerError: null
	at fun.lewisdev.inventoryfull.utils.reflection.Titles.<clinit>(Titles.java:64) ~[?:?]
	at fun.lewisdev.inventoryfull.alert.AlertManager.sendTitle(AlertManager.java:52) ~[?:?]
	at fun.lewisdev.inventoryfull.alert.AlertManager.sendAlerts(AlertManager.java:33) ~[?:?]
	at fun.lewisdev.inventoryfull.listeners.BlockBreakListener.onBlockBreak(BlockBreakListener.java:60) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor668.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1271]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Purpur-1271]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1271]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1271]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:401) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:355) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:290) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1787) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1271]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1422) ~[patched_1.17.1.jar:git-Purpur-1271]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Purpur-1271]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1400) ~[patched_1.17.1.jar:git-Purpur-1271]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1393) ~[patched_1.17.1.jar:git-Purpur-1271]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1532) ~[patched_1.17.1.jar:git-Purpur-1271]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1271]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1271]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.isClassAccessible(MethodHandles.java:3680) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.checkSymbolicClass(MethodHandles.java:3674) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3639) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.findGetter(MethodHandles.java:3020) ~[?:?]
	at fun.lewisdev.inventoryfull.utils.reflection.ReflectionUtils.<clinit>(ReflectionUtils.java:49) ~[?:?]
	... 29 more
```

**Comment by ItsLewizzz** [comment]
Fixed in v3.0.0.
